import {
  User,
  Company,
  CompanyMember,
  Invitation,
  WeeklySchedule,
  Meeting,
  Notification,
  SlotSuggestion,
} from "@/types";

export const currentUser: User = {
  id: "u-001",
  email: "adam@acmecorp.com",
  full_name: "Adam Reynolds",
  avatar_url: null,
  timezone: "America/New_York",
  created_at: "2026-01-10T08:00:00Z",
};

export const users: User[] = [
  currentUser,
  {
    id: "u-002",
    email: "jane@acmecorp.com",
    full_name: "Jane Smith",
    avatar_url: null,
    timezone: "America/Chicago",
    created_at: "2026-01-12T10:00:00Z",
  },
  {
    id: "u-003",
    email: "mike@acmecorp.com",
    full_name: "Mike Chen",
    avatar_url: null,
    timezone: "America/Los_Angeles",
    created_at: "2026-01-15T14:00:00Z",
  },
  {
    id: "u-004",
    email: "sara@acmecorp.com",
    full_name: "Sara Johnson",
    avatar_url: null,
    timezone: "Europe/London",
    created_at: "2026-01-20T09:00:00Z",
  },
  {
    id: "u-005",
    email: "tom@acmecorp.com",
    full_name: "Tom Baker",
    avatar_url: null,
    timezone: "America/New_York",
    created_at: "2026-02-01T11:00:00Z",
  },
];

export const companies: Company[] = [
  {
    id: "c-001",
    name: "Acme Corp",
    slug: "acme-corp",
    owner_id: "u-001",
    created_at: "2026-01-10T08:00:00Z",
  },
  {
    id: "c-002",
    name: "Globex Industries",
    slug: "globex",
    owner_id: "u-001",
    created_at: "2026-02-01T08:00:00Z",
  },
];

export const companyMembers: CompanyMember[] = [
  {
    id: "cm-001",
    company_id: "c-001",
    user_id: "u-001",
    role: "admin",
    joined_at: "2026-01-10T08:00:00Z",
    user: users[0],
    availability: "available",
  },
  {
    id: "cm-002",
    company_id: "c-001",
    user_id: "u-002",
    role: "team_lead",
    joined_at: "2026-01-12T10:00:00Z",
    user: users[1],
    availability: "in_meeting",
    current_activity: "Q1 Planning Review",
  },
  {
    id: "cm-003",
    company_id: "c-001",
    user_id: "u-003",
    role: "member",
    joined_at: "2026-01-15T14:00:00Z",
    user: users[2],
    availability: "busy",
    current_activity: "Deep work block",
  },
  {
    id: "cm-004",
    company_id: "c-001",
    user_id: "u-004",
    role: "member",
    joined_at: "2026-01-20T09:00:00Z",
    user: users[3],
    availability: "available",
  },
  {
    id: "cm-005",
    company_id: "c-001",
    user_id: "u-005",
    role: "member",
    joined_at: "2026-02-01T11:00:00Z",
    user: users[4],
    availability: "offline",
  },
];

export const invitations: Invitation[] = [
  {
    id: "inv-001",
    company_id: "c-001",
    email: "newguy@acmecorp.com",
    role: "member",
    invited_by: "u-001",
    accepted_at: null,
    created_at: "2026-02-20T09:00:00Z",
  },
  {
    id: "inv-002",
    company_id: "c-001",
    email: "designer@acmecorp.com",
    role: "member",
    invited_by: "u-001",
    accepted_at: null,
    created_at: "2026-02-18T14:00:00Z",
  },
];

export const weeklySchedule: WeeklySchedule = {
  id: "ws-001",
  user_id: "u-001",
  company_id: "c-001",
  is_active: true,
  created_at: "2026-01-10T08:00:00Z",
  blocks: [
    {
      id: "sb-001",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 1,
      start_time: "09:00",
      end_time: "12:00",
      label: "Morning availability",
    },
    {
      id: "sb-002",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 1,
      start_time: "13:00",
      end_time: "17:00",
      label: "Afternoon availability",
    },
    {
      id: "sb-003",
      schedule_id: "ws-001",
      block_type: "busy",
      day_of_week: 1,
      start_time: "12:00",
      end_time: "13:00",
      label: "Lunch",
    },
    {
      id: "sb-004",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 2,
      start_time: "09:00",
      end_time: "12:00",
      label: null,
    },
    {
      id: "sb-005",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 2,
      start_time: "14:00",
      end_time: "17:00",
      label: null,
    },
    {
      id: "sb-006",
      schedule_id: "ws-001",
      block_type: "busy",
      day_of_week: 2,
      start_time: "12:00",
      end_time: "14:00",
      label: "Deep work",
    },
    {
      id: "sb-007",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 3,
      start_time: "10:00",
      end_time: "16:00",
      label: null,
    },
    {
      id: "sb-008",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 4,
      start_time: "09:00",
      end_time: "17:00",
      label: null,
    },
    {
      id: "sb-009",
      schedule_id: "ws-001",
      block_type: "available",
      day_of_week: 5,
      start_time: "09:00",
      end_time: "13:00",
      label: "Friday morning",
    },
  ],
};

export const meetings: Meeting[] = [
  {
    id: "m-001",
    company_id: "c-001",
    created_by: "u-001",
    title: "Q1 Planning Review",
    description: "Review Q1 goals and set priorities for the upcoming quarter.",
    duration_minutes: 60,
    start_at: "2026-02-24T14:00:00Z",
    end_at: "2026-02-24T15:00:00Z",
    status: "scheduled",
    has_conflict: false,
    google_event_id: "gcal-evt-001",
    created_at: "2026-02-20T10:00:00Z",
    creator: users[0],
    attendees: [
      {
        id: "ma-001",
        meeting_id: "m-001",
        user_id: "u-001",
        is_required: true,
        gcal_connected: true,
        google_event_id: "gcal-evt-001a",
        user: users[0],
      },
      {
        id: "ma-002",
        meeting_id: "m-001",
        user_id: "u-002",
        is_required: true,
        gcal_connected: true,
        google_event_id: "gcal-evt-001b",
        user: users[1],
      },
      {
        id: "ma-003",
        meeting_id: "m-001",
        user_id: "u-003",
        is_required: true,
        gcal_connected: false,
        google_event_id: null,
        user: users[2],
      },
    ],
  },
  {
    id: "m-002",
    company_id: "c-001",
    created_by: "u-001",
    title: "Design System Sync",
    description: "Align on component library updates and new patterns.",
    duration_minutes: 30,
    start_at: "2026-02-25T10:00:00Z",
    end_at: "2026-02-25T10:30:00Z",
    status: "scheduled",
    has_conflict: false,
    google_event_id: "gcal-evt-002",
    created_at: "2026-02-19T15:00:00Z",
    creator: users[0],
    attendees: [
      {
        id: "ma-004",
        meeting_id: "m-002",
        user_id: "u-001",
        is_required: true,
        gcal_connected: true,
        google_event_id: null,
        user: users[0],
      },
      {
        id: "ma-005",
        meeting_id: "m-002",
        user_id: "u-004",
        is_required: true,
        gcal_connected: true,
        google_event_id: null,
        user: users[3],
      },
    ],
  },
  {
    id: "m-003",
    company_id: "c-001",
    created_by: "u-002",
    title: "Sprint Retrospective",
    description: "Reflect on the last sprint and identify improvements.",
    duration_minutes: 45,
    start_at: "2026-02-26T16:00:00Z",
    end_at: "2026-02-26T16:45:00Z",
    status: "scheduled",
    has_conflict: true,
    google_event_id: null,
    created_at: "2026-02-18T09:00:00Z",
    creator: users[1],
    attendees: [
      {
        id: "ma-006",
        meeting_id: "m-003",
        user_id: "u-002",
        is_required: true,
        gcal_connected: true,
        google_event_id: null,
        user: users[1],
      },
      {
        id: "ma-007",
        meeting_id: "m-003",
        user_id: "u-003",
        is_required: true,
        gcal_connected: false,
        google_event_id: null,
        user: users[2],
      },
      {
        id: "ma-008",
        meeting_id: "m-003",
        user_id: "u-005",
        is_required: false,
        gcal_connected: true,
        google_event_id: null,
        user: users[4],
      },
    ],
  },
  {
    id: "m-004",
    company_id: "c-001",
    created_by: "u-001",
    title: "Client Onboarding Call",
    description: null,
    duration_minutes: 60,
    start_at: null,
    end_at: null,
    status: "draft",
    has_conflict: false,
    google_event_id: null,
    created_at: "2026-02-22T08:00:00Z",
    creator: users[0],
    attendees: [
      {
        id: "ma-009",
        meeting_id: "m-004",
        user_id: "u-001",
        is_required: true,
        gcal_connected: true,
        google_event_id: null,
        user: users[0],
      },
      {
        id: "ma-010",
        meeting_id: "m-004",
        user_id: "u-004",
        is_required: true,
        gcal_connected: true,
        google_event_id: null,
        user: users[3],
      },
    ],
  },
  {
    id: "m-005",
    company_id: "c-001",
    created_by: "u-001",
    title: "Budget Review",
    description: "Review Q1 budget allocation and spending.",
    duration_minutes: 30,
    start_at: "2026-02-21T11:00:00Z",
    end_at: "2026-02-21T11:30:00Z",
    status: "cancelled",
    has_conflict: false,
    google_event_id: null,
    created_at: "2026-02-15T08:00:00Z",
    creator: users[0],
  },
];

export const notifications: Notification[] = [
  {
    id: "n-001",
    user_id: "u-001",
    type: "meeting_created",
    payload: { meeting_id: "m-003", title: "Sprint Retrospective" },
    read: false,
    created_at: "2026-02-22T09:00:00Z",
  },
  {
    id: "n-002",
    user_id: "u-001",
    type: "invited",
    payload: { company_name: "Globex Industries" },
    read: false,
    created_at: "2026-02-21T14:00:00Z",
  },
  {
    id: "n-003",
    user_id: "u-001",
    type: "meeting_updated",
    payload: { meeting_id: "m-001", title: "Q1 Planning Review" },
    read: true,
    created_at: "2026-02-20T11:00:00Z",
  },
];

export const slotSuggestions: SlotSuggestion[] = [
  {
    start: "2026-03-02T14:00:00Z",
    end: "2026-03-02T15:00:00Z",
    score: 95,
    has_conflict: false,
    free_count: 5,
    total_count: 5,
    conflicts: [],
  },
  {
    start: "2026-03-03T10:00:00Z",
    end: "2026-03-03T11:00:00Z",
    score: 90,
    has_conflict: false,
    free_count: 5,
    total_count: 5,
    conflicts: [],
  },
  {
    start: "2026-03-04T15:00:00Z",
    end: "2026-03-04T16:00:00Z",
    score: 78,
    has_conflict: true,
    free_count: 4,
    total_count: 5,
    conflicts: [
      {
        user_id: "u-004",
        name: "Sara Johnson",
        reason: "google_calendar_event",
        event_summary: "1:1 with Manager",
      },
    ],
  },
  {
    start: "2026-03-05T09:00:00Z",
    end: "2026-03-05T10:00:00Z",
    score: 72,
    has_conflict: true,
    free_count: 3,
    total_count: 5,
    conflicts: [
      {
        user_id: "u-003",
        name: "Mike Chen",
        reason: "weekly_schedule_busy",
      },
      {
        user_id: "u-005",
        name: "Tom Baker",
        reason: "google_calendar_event",
        event_summary: "Team standup",
      },
    ],
  },
];
